MCMC metallicities for low-z LLS
pyigm/pyigm pull request #116
Opened 2017-05-29 19:09 UTC by cwotta

Updates to M. Fumagalli's MCMC codes, including new documentation and codes for how to go from measurements of (observed) column densities to running MCMC to extracting metallicities.

Not included are Cloudy photoionization grids.

2017-05-30 11:55 UTC, profxj requested changes

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/MCMC_initial_guesses-full_list.dat
> +##Run_now?  Sightline                 met_guess    dens_guess   carbalpha_guess   carbalpha   logUconstraint   UVB    Notes
Are these example files?  Seem fine, but just want to check

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/README-understanding_MCMC_output.md
> +# Understanding MCMC output (*.pkl format files)
This is helpful.  Thanks!

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/README.md
> +## Create MCMC input files
Also, very helpful!  Am wondering if the folder should be 
renamed to something like MCMC-Metallicitites ?

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/UVB_HM05.dat
> +# The UVB spectrum (quasars+galaxies model) HM05
I'm not sure what this file is for, but I feel it should
go in pyigm/data/euvb

Please make it so.

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/cloudyiongrid.py
> +"""
Code like this needs to go in pyigm/ probably in 
pyigm.metallicity

Thanks

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/cloudyiongrid.py
> +        self.root="n{0}_r{1}_c{2}_Z{3}".format(self.density,self.redshift,self.column,self.metal)
Is this Python3 compatible?  Probably

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/cloudyiongrid.py
> +        fil=open('Scripts/richards_qsosed.txt')
This will need to have package 'wrappers'.  

I prefer to use resource_file in pkg_resources

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/cloudyiongrid.py
> +        inrad=1e5 #pc
How about astropy.units ?

I guess that is overkill here.

As I type this, I remind myself that pyigm already
has code for CUBA in pyigm.euvb

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/cloudyiongrid.py
> +    def initcuba(self):
This should go into the cuba.py module.

I can do that if you wish.

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/cloudyiongrid.py
> +            print "Check model... Something is wrong!"
Not Python3 compaitble.

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/cloudyiongrid.py
> +                print "Column not found"
Python3

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/generate_pdf.py
> +
Also should be in pyigm.metallicity

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/getionisation.py
> +"""
pyigm.metallicity

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/getionisation.py
> +if __name__ == "__main__":
Not sure about this Main function.  Maybe strip out.

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/input_files/mcmc.QSO1234+5678_z0.123456.in
> +name                                            zabs      ezabs         ion     logn    elogn  flag              sample
I'm ok with these being in pyigm, but they should
be in the pyigm.data folder somewhere.

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/mcmc_met.py
> +"""
I'm not sure about this module.  Is it specific to 
your work or more generic?    Either way, if it stays
then it should go in pyigm.metallciity

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/mcmc_met.py
> +    if str(carbalpha_use).lower() == 'false':
We should think of a nicer way of sharing the Cloudy grids (they are too big for pyigm).  Could stage on my machine in UCSC (next to igmspec).

Thoughts @mifumagalli ??

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/mcmc_met.py
> +    print 'Ready to run mcmc for {}'.format(sy)
Python 3

2017-05-30 11:55 UTC, profxj commented on docs/LLS_Metallicities-Wotta/mcmc_met.py
> +    guesses_file = "MCMC_initial_guesses-run_me.dat"
These need to be input

2017-05-30 11:55 UTC, profxj commented on pyigm/metallicity/mcmc.py
> +sys.path.append(os.getcwd())
Is this necessary?  Shouldn't be.

2017-05-30 11:55 UTC, profxj commented on pyigm/metallicity/mcmc.py
> +    The only two UVBs for this are HM05 and HM12 because that's all I have packaged up.
Define logU, redshift, UVB in the Parameters docs

2017-05-30 11:55 UTC, profxj commented on pyigm/metallicity/mcmc.py
> +    The only two UVBs for this are HM05 and HM12 because that's all I have packaged up.
And what does this function return?

2017-05-30 11:55 UTC, profxj commented on pyigm/metallicity/mcmc.py
> +        self.logUconstraint=str(logUconstraint)
Why convert to str ?

2017-05-30 11:55 UTC, profxj commented on pyigm/metallicity/mcmc.py
> +        emc.logUconstraint=self.logUconstraint
If emc needs a str then recast it here.

2017-05-30 11:55 UTC, profxj commented on pyigm/metallicity/mcmc.py
> +        if self.logUconstraint.lower() == 'true':
Let's use a bool here

2017-05-30 11:55 UTC, profxj commented on pyigm/metallicity/mcmc.py
> +        nsamp=np.max([nsamp,300])
Maybe make this 300 a default parameter above?
e.g.  min_nsamp

2017-05-30 11:55 UTC, profxj commented on pyigm/scripts/pyigm_mtlmcmc.py
> +    parser.add_argument('-logUconstraint', type=str, help='Should we use logU constraint on density')
Maybe we should strip this off to a standalone script?

2017-05-30 11:56 UTC, profxj commented
@cwotta -- Thanks so much for this!  I've put in a lot of comments but there
was a lot here.  And, I'm happy to take on any of this.  Maybe we should
discuss briefly when you have the time.

2017-07-04 00:57 UTC, cwotta commented on docs/LLS_Metallicities-Wotta/MCMC_initial_guesses-full_list.dat
> +##Run_now?  Sightline                 met_guess    dens_guess   carbalpha_guess   carbalpha   logUconstraint   UVB    Notes
Yes, they are example files.  Initial guesses for the MCMC ball and a couple of other options.

2017-07-04 00:59 UTC, cwotta commented on docs/LLS_Metallicities-Wotta/README.md
> +## Create MCMC input files
I believe you are referring to the "docs/LLS_Metallicities-Wotta" itself, wondering if it should be "docs/MCMC-Metallicities".  Is that correct?  Sounds good

2017-07-04 01:00 UTC, cwotta commented on docs/LLS_Metallicities-Wotta/UVB_HM05.dat
> +# The UVB spectrum (quasars+galaxies model) HM05
Done.

2017-07-04 01:01 UTC, cwotta commented on docs/LLS_Metallicities-Wotta/cloudyiongrid.py
> +"""
It's in pyigm.euvb as per our conversation at Durham.

2017-07-04 01:02 UTC, cwotta commented on docs/LLS_Metallicities-Wotta/cloudyiongrid.py
> +        fil=open('Scripts/richards_qsosed.txt')
This was Michele's.  I'm not sure where that file is, so I can't put it anywhere.

2017-07-04 01:02 UTC, cwotta commented on docs/LLS_Metallicities-Wotta/cloudyiongrid.py
> +            print "Check model... Something is wrong!"
Fixed all "Python3 print compatibility" issues, I believe.

2017-07-04 01:04 UTC, cwotta commented on docs/LLS_Metallicities-Wotta/generate_pdf.py
> +
Done.

2017-07-04 01:06 UTC, cwotta commented on docs/LLS_Metallicities-Wotta/getionisation.py
> +if __name__ == "__main__":
I'm not sure, either.  It was meant for creating save files/plots with ionization information, so it's meant to be called from the command line.  But if you're still questioning, ask the boss  ;)

2017-07-04 01:07 UTC, cwotta commented on docs/LLS_Metallicities-Wotta/mcmc_met.py
> +"""
It was absorbed into `pyigm_mtlmcmc.py` as per our conversation at Durham.  There is a new `--wotta` option in there that allows you to read in the guesses file, then passes that off to the preexisting function.

2017-07-04 01:09 UTC, cwotta commented on docs/LLS_Metallicities-Wotta/mcmc_met.py
> +    if str(carbalpha_use).lower() == 'false':
Yes.  The ones I have total ~20--25 GB.  I know I have several duplicates of @mifumagalli as well as some of my own.

2017-07-04 01:11 UTC, cwotta commented on docs/LLS_Metallicities-Wotta/mcmc_met.py
> +    guesses_file = "MCMC_initial_guesses-run_me.dat"
Done.  I'll have to update the docs once I get everything sorted out.  But how to call `pyigm_mtlmcmc.py` with the `--wotta` option is listed via a comment at the bottom of that file.  It'll get to the docs eventually.  I need to make sure things are working first.

2017-07-04 01:12 UTC, cwotta commented on pyigm/metallicity/mcmc.py
> +sys.path.append(os.getcwd())
Not after I moved `UVB_HM05.dat` and `UVB_HM12.dat` into `pyigm/pyigm/data/euvb/` and then used `pkg_resources` to locate them.  Removed.

2017-07-04 01:14 UTC, cwotta commented on pyigm/metallicity/mcmc.py
> +        self.logUconstraint=str(logUconstraint)
For annoying "These are passed as input from a text file... So how to compare input `True` and `False` (which are strings) to booleans?" reasons, as discussed in Durham.  This is a kludge, I suppose.

2017-07-04 01:15 UTC, cwotta commented on pyigm/metallicity/mcmc.py
> +        emc.logUconstraint=self.logUconstraint
Done.  Not necessary, but certainly can't hurt.

2017-07-04 01:15 UTC, cwotta commented on pyigm/metallicity/mcmc.py
> +        if self.logUconstraint.lower() == 'true':
See above.

2017-07-04 01:15 UTC, cwotta commented on pyigm/metallicity/mcmc.py
> +        nsamp=np.max([nsamp,300])
Done.

2017-07-07 12:41 UTC, profxj commented on pyigm/metallicity/mcmc.py
> +              outsave='emceeout', optim=False, effnhi=True, testing=False, nwalkers_min=400, nsamp_min=400):
Are these minimum parameters defined in the doc string?
If not, please add them.

2017-07-07 12:43 UTC, profxj commented
Thanks for adding all of these.

I'm now approving.  If you are done @cwotta , let me know
and I'll merge.

2017-07-07 12:43 UTC, profxj approved these changes

2017-07-27 15:32 UTC, merged