Wotta - plot formatting updates and create MCMC_output.py
pyigm/pyigm pull request #157
Opened 2017-11-10 19:53 UTC by cwotta

(1) A small update to mcmc.py that affects plot title positioning and x-axis
(2) Small Python3 compatibility fixes (mostly *.pkl file-related)
(3) Creation of 2 files:
(3a) MCMC_output.py -- class that handles output *.pkl/*.hd5 files, for grabbing desired data on a large scale.  Documentation is at the top for easier finding (will likely refer to it each time), not within each function.
(3b) README_python_get_pdf_cdf.py -- example of how to use MCMC_output.py

2017-11-14 19:23 UTC, profxj requested changes
Just a few things to fuss with.

Thanks for all of this!

2017-11-14 19:23 UTC, profxj commented on docs/LLS_Metallicities-Wotta/README_python_get_pdf_cdf.py
> +##Example: How to get walkers or create a PDF and CDF
If this is meant as a tutorial of sorts,
can we make it a Notebook instead?

I should prefer that for stuff within docs/

2017-11-14 19:23 UTC, profxj commented on pyigm/metallicity/MCMC_output.py
> +import numpy as np
Please start this module off with a doc description
of what it is for.  Am not sure myself.

2017-11-14 19:23 UTC, profxj commented on pyigm/metallicity/MCMC_output.py
> +class MCMC_output(object):
this looks great!

2017-11-14 20:21 UTC, cwotta commented
Requested changes have been made.  I have been working on updating the MCMC_output class (a few large changes), but I need to test more, before updating here.

2017-11-15 20:27 UTC, profxj commented
roger that, @cwotta 

Merge when you are happy.

2017-11-15 20:28 UTC, profxj approved these changes

2017-11-15 20:51 UTC, merged