CGM from systems
pyigm/pyigm pull request #82
Opened 2016-12-29 17:01 UTC by profxj

Generates CGM objects from absorption systems and galaxies.

Tests but no rst docs.

2016-12-31 15:01 UTC, jnburchett requested changes

2016-12-31 15:01 UTC, jnburchett commented on pyigm/cgm/utils.py
> +    dv = ltu.v_from_z(galaxy.z, igm_z)
I get a DeprecationWarning suggesting we "use dv_from_z() instead".

2016-12-31 15:01 UTC, jnburchett commented on pyigm/igm/igmsightline.py
> +        jsonfile
Do the jsonfile contents adhere to some particular format?  Might be helpful to list required quantities defined within the file (RA, DEC, zem, name).

2016-12-31 15:01 UTC, jnburchett commented on pyigm/cgm/tests/test_init_cgm.py
> +    cgm_list = cgm_from_galaxy_igmsystems(galaxy, igmsys, chk_lowz=False)
I really need to knock out this chk_lowz feature...

2016-12-31 15:01 UTC, jnburchett commented on pyigm/cgm/tests/test_init_cgm.py
> +    cgm_list = cgm_from_galaxy_igmsystems(galaxy, igmsys, chk_lowz=False)
It turns out the DeprecationWarning doesn't allow the instantiation.

2017-01-03 16:47 UTC, profxj commented on pyigm/cgm/utils.py
> +    dv = ltu.v_from_z(galaxy.z, igm_z)
Fixed.

2017-01-03 16:50 UTC, profxj commented on pyigm/igm/igmsightline.py
> +        jsonfile
added to docs

2017-01-03 16:53 UTC, profxj commented on pyigm/cgm/tests/test_init_cgm.py
> +    cgm_list = cgm_from_galaxy_igmsystems(galaxy, igmsys, chk_lowz=False)
Test modified.  Passing on my laptop.

2017-01-04 23:12 UTC, jnburchett approved these changes

2017-01-04 23:15 UTC, jnburchett commented
For some reason, a Python 3.4 check is failing on test_make_igmsystems().  I am still running Python 2.7, so I of course do not get the AssertionError found above.  Please merge if you can live with this.

2017-01-05 16:31 UTC, profxj commented
Passing tests now.  Needed the linetools update.
Merging.

2017-01-05 16:31 UTC, merged