Call xspec from inside igmguesses
pyigm/pyigm pull request #84
Opened 2017-01-06 02:06 UTC by profxj

Adds keystroke "&" to enable the igmguesses user to launch
a new widget (a modified xspec).

It also converts the list of componetns into AbsSystems
and each of these is plotted (with unique color coding).

No tests or docs (aside from top doc string).

It may make sense to push the new Dialog into linetools.
Don't merge until we decide on that.

2017-01-06 17:01 UTC, ntejos commented
What would be the main idea of having xspec loaded within IGMGuesses?

2017-01-06 17:03 UTC, profxj commented
1. View the full spectrum vs. wavelength
1. Inspect which lines are still not identified (and which are)

2017-01-12 15:50 UTC, ntejos commented on pyigm/guis/igmguesses.py
> +        self.close()
As discussed, may be better to move this ExSpecDialog to linetools.

2017-01-30 15:12 UTC, ntejos requested changes
Looks good, please merge after addressing the comment.

2017-01-30 15:12 UTC, ntejos commented on pyigm/guis/igmguesses.py
> +        zlim_comp = comp.zcomp + (1 + comp.zcomp) * (comp_vlim_mks / c_kms)
Use `ltu.z_from_dv()` instead

2017-01-31 01:01 UTC, profxj commented on pyigm/guis/igmguesses.py
> +        zlim_comp = comp.zcomp + (1 + comp.zcomp) * (comp_vlim_mks / c_kms)
replaced as requested.

2017-01-31 01:55 UTC, profxj commented
Merging

2017-01-31 01:55 UTC, merged