Peculiar velocity corrections
pyigm/pyigm pull request #88
Opened 2017-02-06 17:34 UTC by jnburchett

Functions to correct for peculiar velocities when calculating distances from redshifts
Includes test

2017-02-08 15:43 UTC, profxj requested changes
Just a few changes requested.
Thanks a ton for doing this.

2017-02-08 15:43 UTC, profxj commented on pyigm/cgm/cgm.py
> +        #if (galaxy.z < 0.05) and chk_lowz:
We can likely remove these lines

2017-02-08 15:43 UTC, profxj commented on pyigm/cgm/tests/test_init_cgm.py
> +    cgm_list = cgm_from_galaxy_igmsystems(galaxy, igmsys, chk_lowz=True)
I think we can eliminate the chk_lowz here and throughout the code.

2017-02-08 15:43 UTC, profxj commented on pyigm/cgm/utils.py
> +    if (galaxy.z < 0.05) and chk_lowz:
Again, remove the chk_lowz.  

Please add a doc above stating how things are different when z<0.05

2017-02-08 15:43 UTC, profxj commented on pyigm/cgm/utils.py
> +        kpc_amin = velcorrdict['scale'].to(u.kpc/u.arcmin)
I take it this one is a proper distance instead of comoving (hardly matters at such low z)

2017-02-08 15:43 UTC, profxj commented on pyigm/cgm/utils.py
> +    clcoords = SkyCoord(clra1950,cldec1950,unit=(u.hourangle,u.degree),frame='fk4',equinox='B1950.0')
B1950 -- Nice!

2017-02-08 15:43 UTC, profxj commented on pyigm/cgm/utils.py
> +    c = 2.99792458e5 * u.km/u.s
Could use astropy.constants.c

2017-02-08 15:43 UTC, profxj commented on pyigm/cgm/utils.py
> +        * np.cos(galcoords_gal.b).value + 296.0 * (u.km/u.s) * np.sin(galcoords_gal.l).value \
Seems odd to see the .value attributes on the sin and cos, 
but I presume this is done right.

2017-02-08 15:43 UTC, profxj commented on pyigm/cgm/utils.py
> +        virgo = 1
I might use True instead of 1 but this is fine.

2017-02-08 15:43 UTC, profxj commented on pyigm/cgm/utils.py
> +        if virgo:
can more than 1 of this hit?

If not, you might use elif.

2017-02-08 15:43 UTC, profxj commented on pyigm/cgm/utils.py
> +    distmod = 5. * np.log10(lumdist.to(u.pc).value) - 5.
Should this be 10pc?  Just checking..

2017-02-11 13:12 UTC, jnburchett commented on pyigm/cgm/cgm.py
> +        #if (galaxy.z < 0.05) and chk_lowz:
yep

2017-02-11 13:14 UTC, jnburchett commented on pyigm/cgm/tests/test_init_cgm.py
> +    cgm_list = cgm_from_galaxy_igmsystems(galaxy, igmsys, chk_lowz=True)
I'd rather not remove the chk_lowz altogether, as some people are made a little uneasy by this correction (e.g., the referee of paper 3).  Also, there are other formalisms for applying this correction, although the one we adopt is the most solid I'm aware of.

2017-02-11 13:17 UTC, jnburchett commented on pyigm/cgm/utils.py
> +        kpc_amin = velcorrdict['scale'].to(u.kpc/u.arcmin)
Added inline comment

2017-02-11 13:17 UTC, jnburchett commented on pyigm/cgm/utils.py
> +    clcoords = SkyCoord(clra1950,cldec1950,unit=(u.hourangle,u.degree),frame='fk4',equinox='B1950.0')
Haha, it's what Mould et al. provide in their paper, so I just kept it consistent.

2017-02-11 13:21 UTC, jnburchett commented on pyigm/cgm/utils.py
> +    c = 2.99792458e5 * u.km/u.s
As you wish

2017-02-11 13:29 UTC, jnburchett commented on pyigm/cgm/utils.py
> +        * np.cos(galcoords_gal.b).value + 296.0 * (u.km/u.s) * np.sin(galcoords_gal.l).value \
Perhaps this is a bit awkward style.  I've moved the .value inside the function argument.

2017-02-11 13:32 UTC, profxj commented on pyigm/cgm/tests/test_init_cgm.py
> +    cgm_list = cgm_from_galaxy_igmsystems(galaxy, igmsys, chk_lowz=True)
ok, but we should probably use a different flag, e.g.
  correct_lowz
or something like that.

2017-02-11 13:35 UTC, jnburchett commented on pyigm/cgm/utils.py
> +        virgo = 1
Changed

2017-02-11 13:40 UTC, jnburchett commented on pyigm/cgm/utils.py
> +        if virgo:
I think, in general, multiple hits could occur, and the next little code block imposes that Shapley supercedes GA supercedes Virgo.

2017-02-11 13:45 UTC, jnburchett commented on pyigm/cgm/utils.py
> +    distmod = 5. * np.log10(lumdist.to(u.pc).value) - 5.
With the distance normalization inside the logarithm, it looks like:  
DM = 5 log_10(d / 10pc)
Should be right.

2017-02-11 14:03 UTC, jnburchett commented on pyigm/cgm/tests/test_init_cgm.py
> +    cgm_list = cgm_from_galaxy_igmsystems(galaxy, igmsys, chk_lowz=True)
Cool.  I've refactored to change the argument/variable name and updated the CGM class definition docstring.

2017-02-11 14:52 UTC, jnburchett commented on pyigm/cgm/utils.py
> +        * np.cos(galcoords_gal.b).value + 296.0 * (u.km/u.s) * np.sin(galcoords_gal.l).value \
Turns out that moving the .value inside the parentheses would feed np.cos degrees when it take radians.  Moved .value back outside.

2017-02-11 16:09 UTC, profxj commented on pyigm/cgm/utils.py
> +    distmod = 5. * np.log10(lumdist.to(u.pc).value) - 5.
Got it.

2017-02-11 16:09 UTC, profxj approved these changes

2017-02-11 16:09 UTC, profxj commented
Merging.

2017-02-11 16:10 UTC, merged