Galaxy CGM
pyigm/pyigm pull request #90
Opened 2017-02-27 13:33 UTC by profxj

Begins the construction of a new Class for our Galaxy's CGM

Ingests Fang+15 OVII data

This is failing Travis and will do so until PR#362 clears in linetools (x-ray lines)

Docs and tests and a Notebook

2017-03-08 03:48 UTC, jnburchett requested changes
A few relatively minor things

2017-03-08 03:48 UTC, jnburchett commented on pyigm/cgm/cgm.py
> +      List of AbsSys classes
Note that cgm_abs is still defined as a list of CGMAbsSys classes in docs/cgm.rst.  Should probably change there too.

2017-03-08 03:48 UTC, jnburchett commented on pyigm/cgm/cgm.py
> +        self.cgm_abs = []   # These will be AbsSystem's *not* CGMAbsSystem
See note above on documentation.  Do other outdated references to the data type of cgm_abs exist?

2017-03-08 03:48 UTC, jnburchett commented on pyigm/abssys/igmsys.py
> +                 self.coord.fk5.ra.to_string(unit=u.hour, sep=':', pad=True),
Is the specification of fk5 for generality here or in anticipation of the MW CGM being more conveniently characterized in galactic coordinates?

2017-03-08 03:48 UTC, jnburchett commented on pyigm/cgm/galaxy.py
> +    cdir : str, optional
Surely these wouldn't need point to the COS-Halos data for this object, right? The CGM base class doesn't require such paths.

2017-03-08 03:48 UTC, jnburchett commented on pyigm/cgm/utils.py
> +        d_Sun = 8.0 * u.kpc
Perhaps 'd_Sun = 8.0 * u.kpc' should be a default argument of calc_rho() instead of hard-coded?  People are still refining this measurement.

2017-03-08 03:48 UTC, jnburchett commented on pyigm/cgm/utils.py
> +      separation in arsec (deg for Galactic)
Typo: 'arsec' -> 'arcsec'

2017-03-08 03:48 UTC, jnburchett commented on pyigm/cgm/galaxy.py
> +        ion: tuple
Type should be 'tuple or str'?

2017-03-08 03:48 UTC, jnburchett commented on pyigm/cgm/galaxy.py
> +                    zem = row['RV']/3e5
For style, maybe use the astropy.constants instead of the 3e5 approximation?

2017-03-08 03:48 UTC, jnburchett commented on pyigm/cgm/galaxy.py
> +            warnings.warn('CosHalos: CGM not found')
Still so COS-Halos-centric?

2017-03-08 03:48 UTC, jnburchett commented on pyigm/cgm/galaxy.py
> +    def write(self, outfil='COS-Halos_sys.tar.gz'):
How about a different default 'outfil' value?

2017-03-08 03:48 UTC, jnburchett commented on pyigm/cgm/galaxy.py
> +          str: field_gal_id
The notation here is a bit confusing.  At first glance, it looks like a need a 'field', a 'gal', and an 'id' if I use a str.

2017-03-08 03:48 UTC, jnburchett commented on pyigm/cgm/utils.py
> +      Calculate for our Galaxy!
We should add guidance in the docstring about ang_sep and correct_lowz!  I think that is my bad, actually.

2017-03-08 14:28 UTC, profxj commented on pyigm/cgm/cgm.py
> +      List of AbsSys classes
Fixed.  In the end, these are CGMAbsSys

2017-03-08 14:28 UTC, profxj commented on pyigm/cgm/cgm.py
> +        self.cgm_abs = []   # These will be AbsSystem's *not* CGMAbsSystem
fixed

2017-03-08 14:28 UTC, profxj commented on pyigm/abssys/igmsys.py
> +                 self.coord.fk5.ra.to_string(unit=u.hour, sep=':', pad=True),
both.  :)

2017-03-08 14:29 UTC, profxj commented on pyigm/cgm/galaxy.py
> +    cdir : str, optional
doc string updated

2017-03-08 14:30 UTC, profxj commented on pyigm/cgm/galaxy.py
> +                    zem = row['RV']/3e5
now c_kms

2017-03-08 14:30 UTC, profxj commented on pyigm/cgm/galaxy.py
> +        ion: tuple
updated, although this method has not yet been tested..

2017-03-08 14:31 UTC, profxj commented on pyigm/cgm/galaxy.py
> +          str: field_gal_id
not yet implemented.  modified

2017-03-08 14:31 UTC, profxj commented on pyigm/cgm/galaxy.py
> +            warnings.warn('CosHalos: CGM not found')
same

2017-03-08 14:33 UTC, profxj commented on pyigm/cgm/utils.py
> +      Calculate for our Galaxy!
added

2017-03-08 14:33 UTC, profxj commented on pyigm/cgm/utils.py
> +      separation in arsec (deg for Galactic)
fixed

2017-03-08 14:34 UTC, profxj commented on pyigm/cgm/utils.py
> +        d_Sun = 8.0 * u.kpc
done

2017-03-08 14:35 UTC, profxj commented
Back at you JB

2017-03-11 17:13 UTC, jnburchett requested changes
Everything looks great...just need to fix reference to Mould et al. for low-z velocity correction.

2017-03-11 17:13 UTC, jnburchett commented on pyigm/cgm/utils.py
> +      Follows Tonry et al.
The velocity correction actually follows Mould et al. 2000.

2017-03-11 17:29 UTC, profxj commented on pyigm/cgm/utils.py
> +      Follows Tonry et al.
corrected

2017-03-11 17:29 UTC, profxj commented
ok, @jnburchett please merge

2017-03-11 17:33 UTC, jnburchett approved these changes

2017-03-11 17:34 UTC, merged